# Site settings
title:          Enda Phelan
description:    "Minimal Jekyll theme for storytellers"
baseurl:        ""
url:            "https://endaphelan.me"

github:         craicoverflow
email:          endaphelan@gmail.com
linkedin:       endaphelan
instagram:      enda.phelan

# Author
author:
  name:         Enda Phelan
  url:          https://endaphelan.me
  email:        endaphelan@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate
  - jemoji 

# Permalinks
permalink:      /:categories/:title
paginate:       5