# Site
title:              Enda Phelan
description:        'Software Engineer @ Red Hat'
bio:                'Enda. 24. Irish. Software Engineer at Red Hat.'
reading_time:       true
words_per_minute:   200
avatar:             'assets/img/me.jpg'
logo:               'assets/img/logo.png'
background:         'assets/img/placeholder-big.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_IE
url:                https://endaphelan.me

# Jekyll
permalink:          /:categories/:title
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   taylantatli

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
#email:
twitter:            PhelanEnda
github-url:         craicoverflow
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:           endaphelan
#xing:              username
instagram:          enda.phelan
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
steam:              username
#dribbble:          username
youtube:            UC1L26uKpDW7ulxUBSi627UQ
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]

# Images
image_cdn:      https://i.imgur.com

defaults:
  -
    scope:
      path:            "assets/**/*.pdf"
    values:
      sitemap:         false