# Site settings
title:          Enda Phelan
description:    "Enda Phelan is a software engineer from Ireland. This is his personal website where he posts about anything and everything, from technology to travel."
baseurl:        ""
url:            http://endaphelan.me
logo:           /assets/jpg/Enda.jpg
lang:           en_IE

# GitHub
github:
  username:     craicoverflow

# Email
email:          
  username:     endaphelan@gmail.com

# LinkedIn
linkedin:
  username:     endaphelan

# Instagram
instagram:
  username:     enda.phelan

# Twitter
twitter:        
  username:     PhelanEnda
  card:         summary

# Author
author:
  name:         Enda Phelan
  url:          http://endaphelan.me
  email:        endaphelan@gmail.com

# Social links
social:
  name: Enda Phelan
  links:
    - https://twitter.com/PhelanEnda
    - https://www.linkedin.com/in/endaphelan
    - https://github.com/craicoverflow
    - https://instagram.com/enda.phelan

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate
  - jemoji 
  - jekyll-seo-tag

# Permalinks
permalink:      /:categories/:title
paginate:       5